# This is our production compose file - not changed for docker-sync or similar

version: "2"
services:
  app-simplest:
    image: alpine
    command: ["sh", "-c", "while sleep 3; do cat /var/www/index.html; done"]
